Bookmark api
today-they-learned/ttl_api pull request #44
Opened 2022-02-02 13:27 UTC by Jin409

## 작업 내용
- 북마크 api
- 없는 게시글 북마킹 방지
- 없는 북마크 삭제 방지
- 같은 유저가 같은 게시글에 대하여 중복 북마킹 방지 

## 기타 사항
- bookmark_destroy_api_view 에서 로그인 되어 있는 유저의 북마크가 아니라면 뜨지 않게 해두었는데 이러한 경우에도 permission이 필요한가요..? 유저가 아니라면 북마크에 접근도 못할 것이라는 생각이 들어서요! 이에 대한 피드백도 부탁드립니다.

2022-02-02 13:29 UTC, shinkeonkim reviewed
음 뭔가 원래 있던 모델 개발 내용과 좀 겹쳐 있는 것 같네요 일단 무시하고 보겠습니다

2022-02-02 13:45 UTC, shinkeonkim requested changes
내용 확인해주시고, 반영해보시면 좋을 것 같습니다

2022-02-02 13:45 UTC, shinkeonkim commented on article/urls.py
```python
from article.views import (
    ArticleListCreateAPIView,
    ArticleRetrieveUpdateDestroyAPIView,
    BookmarkListCreateAPIView,
    BookmarkDestroyAPIView
)
```
위와같이 나열하시면 될 것 같습니다.

2022-02-02 13:45 UTC, shinkeonkim commented on article/views/bookmark_list_create_api_view.py
> +        return self.list(request, *args, **kwargs)
ListAPIView는 여기에 같이 붙어 있으면 안될 것 같습니다. 그냥 CreateAPIView로 하시면 될 것 같아요.

북마크 목록은 유저 기준이라서 user쪽 뷰에 따로 추가하는게 좋을 것 같아요

2022-02-02 13:45 UTC, shinkeonkim commented on article/views/bookmark_list_create_api_view.py
> +                                generics.ListCreateAPIView, generics.GenericAPIView):
p3: GenericAPIView 이건 이미 generics.ListCreateAPIView(CreateAPIView)에서 상속하고 있지 않나요? 없어도 될 것 같습니다.

2022-02-02 13:45 UTC, shinkeonkim commented on article/views/bookmark_list_create_api_view.py
> +            is_article_exist = self.perform_create(serializer,article_id)
이걸 쉽게 할 수 있게, django에는 get_or_create가 있습니다.

(그리고 409 status는 이럴때 쓰기엔 좀 애매한것 같습니다. 400? 402? 정도가 더 좋지 않을까요?)

```
from django.shortcuts import get_object_or_404

...

def create(self, request, article_id, *args, **kwargs):
    article = get_object_or_404(Article, id = article_id)
    bookmark, is_bookmarked = Bookmark.objects.get_or_create(user=self.current_user, article=article)

    if is_bookmarked:
         return Response(status=status.HTTP_400_BAD_REQUEST)

    serializer = self.get_serializer(data=bookmark)
    serializer.is_valid(raise_exception=True)
    headers = self.get_success_headers(serializer.data)
    return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)
```

참고 > https://whatisthenext.tistory.com/121

2022-02-02 13:45 UTC, shinkeonkim commented on article/views/bookmark_list_create_api_view.py
> +            return {}
q: 이건 왜 있나요?

2022-02-02 13:45 UTC, shinkeonkim commented on article/views/bookmark_list_create_api_view.py
> +            return False
음 여기에서 except하지 않고 create 메서드에서 get_object_or_404를 이용하면 좋을 것 같네요
(위 코드에 반영해둘게요)

2022-02-02 13:54 UTC, Jin409 commented on article/views/bookmark_list_create_api_view.py
> +            return {}
createmodelmixin 에 속한 함수들 전부 가져온건데.. 뺄까요?

2022-02-02 13:56 UTC, shinkeonkim commented on article/views/bookmark_list_create_api_view.py
> +            return {}
그걸 상속한 상황이니 가져올 필요없을것같습니다

2022-02-04 10:36 UTC, shinkeonkim commented on article/views/bookmark_destroy_api_view.py
> +            return Response(status=status.HTTP_404_NOT_FOUND)
p3: get_object_or_404를 쓰면 되지 않을까요?

2022-02-04 10:36 UTC, shinkeonkim commented on article/views/bookmark_create_api_view.py
> +        serializer.save(user=self.current_user,article=article)
perform_create도 필요없어졌지 않을까유 ㅎㅎ
def create에서 호출되는 순서를 쭉 보시면 될 것 같아요

2022-02-04 10:54 UTC, Jin409 commented on article/views/bookmark_create_api_view.py
> +        serializer.save(user=self.current_user,article=article)
앗.. 그렇네요 article 정보를 추가적으로 넘겨줘야 한다고 생각했는데 이미 들어가있는거네요.. 수정하겠습니다!

2022-02-04 12:15 UTC, shinkeonkim approved these changes

2022-02-04 12:15 UTC, merged